name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: '30.0.3'

    - name: Install NDK
      run: |
        sudo mkdir -p $ANDROID_HOME/ndk/
        sudo wget -q https://dl.google.com/android/repository/android-ndk-r27-linux.zip -O android-ndk-r27.zip
        sudo unzip -q android-ndk-r27.zip -d $ANDROID_HOME/ndk/
        sudo mv $ANDROID_HOME/ndk/android-ndk-r27 $ANDROID_HOME/ndk/27.0.0

    - name: Prepare local.properties
      run: echo "ndk.dir=$ANDROID_HOME/ndk/27.0.0" > $GITHUB_WORKSPACE/local.properties

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
