name: Build APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: '30.0.3'

    - name: Install NDK
      run: |
        sudo mkdir -p $ANDROID_HOME/ndk/
        sudo wget -q https://dl.google.com/android/repository/android-ndk-r26c-linux.zip -O android-ndk-r26c-linux.zip
        sudo unzip -q android-ndk-r26c-linux.zip -d $ANDROID_HOME/ndk/
        sudo mv $ANDROID_HOME/ndk/android-ndk-r26c $ANDROID_HOME/ndk/26.2.11394342

    - name: Prepare local.properties
      run: echo "ndk.dir=$ANDROID_HOME/ndk/26.2.11394342" > $GITHUB_WORKSPACE/local.properties

    - name: release apk sign
      run: |
        echo "给apk增加签名"
        #cp $GITHUB_WORKSPACE/.github/workflows/android.keystore $GITHUB_WORKSPACE/app/android.keystore
        wget https://github.com/xuexiangjys/XUpdate/raw/master/.github/workflows/android.keystore -O $GITHUB_WORKSPACE/.github/workflows/android.keystore
        sed '$a\RELEASE_STORE_FILE=./android.keystore'          $GITHUB_WORKSPACE/gradle.properties -i
      
    - name: build with gradle
      run: |
         echo "开始进行release构建"
         chmod +x gradlew
         ./gradlew app:assemble

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
